version: 2

sources:
  - name: weather
    database: dev_ingest  
    schema: weather  
    tables:
      - name: current_weather


  - name: stocks
    database: dev_ingest  
    schema: stocks 
    tables:
      - name: time_series_daily

  - name: social
    database: dev_ingest  
    schema: social 
    tables:
      - name: ratings
